name: Publish Stable

on:
  push:
    branches: [master]

jobs:
  publish:
    permissions:
      contents: write
    uses: nano-step/shared-workflows/.github/workflows/publish-stable.yml@v1
    permissions:
      contents: write
    with:
      package-name: "@kokorolx/ai-sandbox-wrapper"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
